apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ora-data184-claim-snapshot-clone
  labels:
    app: database
    version: 18.4.0.1
spec:
  storageClassName: px-ora-csi-sc
  dataSource:
    name: ora-data184-claim-snapshot
    kind: VolumeSnapshot
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
